from __future__ import annotations

from dataclasses import dataclass

SCORE_VERSION = "pilot-v3"
REDUNDANCY_THRESHOLD = 0.80
DEFAULT_SUMMARY_LIMIT = 20
PUNCTUATION_GAP_REJECT_THRESHOLD = 0.75
ASSOCIATION_KEEP_THRESHOLD = 0.30
BOUNDARY_KEEP_THRESHOLD = 1.50
BOUNDARY_KEEP_ASSOCIATION_FLOOR = 0.10
LEXICAL_KEEP_THRESHOLD = 6.0
LEXICAL_ONLY_ASSOCIATION_FLOOR = 0.20
SPECIFICITY_SINGLE_SHOW_REJECT_DISPERSION = 1
SPECIFICITY_HARD_SHOW_DISPERSION = 3
SPECIFICITY_HARD_MAX_SHOW_SHARE = 0.70
SPECIFICITY_HARD_TOP2_SHOW_SHARE = 0.90
SPECIFICITY_SOFT_SHOW_DISPERSION = 5
SPECIFICITY_SOFT_MAX_SHOW_SHARE = 0.60
SPECIFICITY_SOFT_TOP2_SHOW_SHARE = 0.85
SPECIFICITY_MAX_PENALTY = 0.15
ONE_GRAM_SPECIFICITY_SHOW_DISPERSION = 3
ONE_GRAM_SPECIFICITY_MAX_SHOW_SHARE = 0.80
ONE_GRAM_SPECIFICITY_MAX_PENALTY = 0.05
DISCARD_FAMILY_SUPPORT = "support_floor"
DISCARD_FAMILY_EDGE_CLITIC = "edge_clitic_gap"
DISCARD_FAMILY_WEAK_MULTIWORD = "weak_multiword"
DISCARD_FAMILY_SHOW_SPECIFICITY = "show_specificity"


@dataclass(frozen=True)
class _LaneSpec:
    ranking_lane: str
    min_raw_frequency: int
    min_episode_dispersion: int


_LANE_SPECS: dict[int, _LaneSpec] = {
    1: _LaneSpec("1gram", 20, 5),
    2: _LaneSpec("2gram", 10, 3),
    3: _LaneSpec("3gram", 10, 3),
}
